### PR TITLE
Adds support for `width`, `height` and `data-*` attributes

### LINKED ISSUE #11: Allow attributes to be passed through on images
It would helpful if you could assign attributes like `height`, `width`, or `data-*` when using this component and have those pass through to the lazy loaded image.

### PR DESCRIPTION
**Pull request by twokul**
fixes #11

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
Awesome, thanks for tackling this!  One question though.  When I try to use this I end up with the `data-` attribute I expect, but I also get an extra attribute `data-person-idbinding="[object Object]"`.

Input:
```
  {{lazy-image url=person.profilePicture alt=person.name height="150"
      width="150" title=person.name class="img-rounded grid" data-person-id=person.id}}
```

Output:
```
<img class="lazy-image" src="https://instagramimages-a.akamaihd.net/profiles/profile_695208774_75sq_1386708366.jpg" 
height="150" width="150" 
data-person-idbinding="[object Object]" data-person-id="18">
```

**Comment by twokul** [comment]
@Dhaulagiri ah, makes sense

**Comment by twokul** [comment]
@Dhaulagiri should be fixed now

**Comment by Dhaulagiri** [comment]
I tried pulling down the latest version of this branch, but I still get the same output

**Comment by twokul** [comment]
@Dhaulagiri mind testing again?

**Comment by Dhaulagiri** [comment]
:+1:  Works great now

**Pull request merged**
