### PR TITLE
do not use width and height if one of them is 0 or unset

### PR DESCRIPTION
**Pull request by givanse**

### CODE REVIEW

**Comment by twokul** [comment]
am I crazy to think that if `width` or `height` are `undefined`, according attributes are not gonna be set on `` tag?

**Comment by givanse** [comment]
I just ran the dummy app without this changes and verified that when the width and height were not passed as arguments of the component, the `` was rendered with `width=0` and `height=0`.

I checked on
* Chrome Version 41.0.2272.101 (64-bit)
* Firefox 36.0.4

I didn't find anything about a default behavior for this type of thing (undefined values) here: http://www.w3.org/TR/html5/embedded-content-0.html#attr-dim-width

After reading that, I tried to use default values of empty string for `width` and `height`, but the value 0 was applied again (same for `null`).

**Comment by givanse** [comment]
I did a little experiment and I think you are right, see: http://jsbin.com/yokinedawi/1/edit?html,output

In practice, the addon doesn't behave like that. Something is turning undefined values to 0.

**Comment by twokul** [comment]
thanks for the patch, dude @givanse

**Pull request merged**
